routelink/client

src/components/Users/Users.tsx

* feat: add "remove users" dialog
* feat: add "edit user" panel
* fix: fix error on render table empty cell

feat: update users component 

---

src/components/Maps/Menu/Menu.tsx

feat: improve `Menu` component in `Maps`

---

src/App.tsx
src/components/Organizations/Organizations.test.tsx
src/components/Organizations/Organizations.tsx
src/components/Organizations/index.tsx
src/components/index.ts
src/layouts/Main.tsx

feat: add orgs components

---

src/components/TransportManagement/TransportManagement.tsx

fix: change name column

---

src/components/TransportManagement/TransportAddForm.tsx

fix: vehicle reg number adding

---

vite.config.ts

fix: loading animation

---

src/components/Analytics/Analytics.tsx
src/components/Analytics/AutoEfficiencyTable.tsx
src/components/Analytics/FuelConsumptionTable.tsx
src/components/Analytics/OvertimeTable.tsx
src/components/Analytics/ServicesTable.tsx
src/components/Analytics/TrafficAccidentTable.tsx

improve styles of `Analytics` component

---

src/components/Organizations/Organizations.tsx
src/models/organization.ts
src/stores/index.ts
src/stores/organizations/index.ts
src/stores/organizations/organizations.ts

Closes #93 
* feat: add support mobx to table "organizations"
* feat: add support mobx to dialog "add organizations"

feat: add `mobx` to `Organization` component

---

CHANGELOG.md
package-lock.json
package.json

* add mobx to Transport component ([#104](https://github.com/routelink/client/issues/104)) ([addae22](https://github.com/routelink/client/commit/addae2246ad9d9233284965ad5147661fd0ab3f7))

🚀 Release/v1.2.0

---

src/components/Modal/Modal.tsx
src/layouts/Sidebar.tsx

Closes #73 
https://github.com/routelink/client/assets/100131721/1a80a1f8-8588-476f-b0ad-2bfb670316b7

fix: incorrect position Modal component

---

src/components/TransportManagement/TransportManagement.tsx
src/components/Users/Users.tsx
src/stores/transport/transport.ts
src/ui/index.ts
src/ui/search/SearchField.tsx
src/ui/search/index.ts

feat: add search to transport table

---

CHANGELOG.md
package-lock.json
package.json

* add and improve components, add new stores ([#115](https://github.com/routelink/client/issues/115)) ([1cd6078](https://github.com/routelink/client/commit/1cd60789a9a7ac5985e64eca09e13cb81ca9898d))
* add search to transport table ([#113](https://github.com/routelink/client/issues/113)) ([d270ae2](https://github.com/routelink/client/commit/d270ae2c77db9436a8781ced7426e6cbabeef326))
* incorrect position Modal component ([#116](https://github.com/routelink/client/issues/116)) ([a54e5be](https://github.com/routelink/client/commit/a54e5beac43c44639a1824be2e9ddaf7e0779a12))

🚀 Release/v1.3.0

---

src/components/Organizations/Organizations.tsx
src/stores/organizations/organizations.ts

Closes #93
* feat: add support `mobx` to dialog `edit organizations`
* fix: change layout component `Organizations` (remove "px")

feat: update component `Organizations` (mobx, layout)

---

src/components/Users/Users.tsx
src/models/index.ts
src/models/role.ts
src/models/user.ts
src/stores/index.ts
src/stores/users/index.ts
src/stores/users/users.ts

*  feat: update `models role`
*  feat: update `models user`
* add support `mobx` to `table users`
* add support `mobx` to dialog `remove users`
* fix: change `layout` component `Users` (remove "px")

feat: update component `Users`

---

.env
.env.test
src/App.test.tsx
src/components/Profile/Dialogs/Avatar.tsx
src/components/Profile/Dialogs/Name.tsx
src/components/Profile/Personal.tsx
src/models/user.ts
src/services/api/api.test.ts
src/services/index.ts
src/services/profile/index.ts
src/services/profile/profile.ts
src/stores/index.ts
src/stores/profile/index.ts
src/stores/profile/profile.test.ts
src/stores/profile/profile.ts

feat: add mobx to profile component

---

src/components/Organizations/Organizations.tsx
src/models/organization.ts
src/stores/organizations/organizations.ts

fix: remove custom types from `mobx` and `models`

update `Organizations` component

---

src/components/Users/Users.tsx

* fix: remove unused variable
* fix: temp fix incorrect pagination (remove variant "all")
* fix: remove custom colors

 update `users` components

---

src/services/index.ts
src/services/organizations/index.ts
src/services/organizations/organizations.ts
src/stores/organizations/organizations.ts

feat: add loading `organisations` list from backend

feat: update `organisations` component

---

src/components/Organizations/Organizations.tsx
src/services/organizations/organizations.ts
src/stores/organizations/organizations.ts

feat: update component organizations
* feat: connect component `organizations` to backend (add create/update/delete operations)
* fix: remove "fantom selections" in `orgs` table rows after remove org(s)
* fix: remove try-catch from orgs service

 feat: update component `organizations`

---

src/components/Organizations/Organizations.tsx

* fix: add load `orgs` list on load component

feat: update `orgs` component

---

src/components/Analytics/ServicesTable.tsx
src/models/service.ts
src/services/analytics/analytics.ts
src/services/analytics/index.ts
src/stores/analytics/analytics.ts
src/stores/analytics/index.ts

feat: add service integration from back for `analytics`

---

src/components/Employees/Dialogs/Create.tsx
src/components/Employees/Dialogs/Update.tsx
src/services/transport/transport.ts

fix: row delete error

---

src/components/Users/DialogUserEdit.tsx

fix: remove `console.log` debug from `users` component

refactor: remove `console.log` debug from `users` component

---

src/components/TransportManagement/TransportManagement.tsx
src/components/TransportManagement/VehicleForm.tsx
src/components/TransportManagement/index.ts
src/models/api/transport.ts
src/services/transport/transport.ts
src/stores/transport/transport.ts
src/ui/table/renderers.tsx

fix: add row and edit row

---

src/components/Analytics/Analytics.tsx
src/components/Analytics/ServicesStepper.tsx
src/components/Analytics/TrafficAccidentTable.tsx
src/models/index.ts
src/models/insure.ts
src/services/analytics/analytics.ts
src/stores/analytics/analytics.ts
src/stores/index.ts

feat: integration of analytics
